/**
 * Universidad del Valle
 * Desarrollo de Software II
 * Tarea - Patron de diseño DAO
 * Abril 11 de 2012
 */

package gui;

/**
 *
 * @author franjav
 */
public class AcercaDe extends javax.swing.JFrame {

    /** Creates new form AcercaDeSGP */
    public AcercaDe() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAcercade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca de");
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabelAcercade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/Acercade.png"))); // NOI18N
        jLabelAcercade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAcercadeMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelAcercade);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelAcercadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAcercadeMouseClicked
        dispose();
    }//GEN-LAST:event_jLabelAcercadeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAcercade;
    // End of variables declaration//GEN-END:variables

}
