/**
 * Universidad del Valle
 * Desarrollo de Software II
 * Tarea - Patron de diseño DAO
 * Abril 11 de 2012
 */

/*
 * GuiPrincipal.java
 *
 * Created on 08-abr-2012, 17:27:52
 * Actualizado: 26-mar-2012, 10:42
 */
package gui;


import gui.controlador.ButtonTabComponent;
import gui.controlador.ControladorGuiPrincipal;
import java.awt.Component;
import javax.swing.JTabbedPane;

/**
 *
 * @author Franjav
 */
public class GuiPrincipal extends javax.swing.JFrame {
    
    private ControladorGuiPrincipal controladorPrincipal;
    private int numeroComponentes;   

    /** Creates new form GuiPrincipal */
    public GuiPrincipal() {        
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void setControladorPrincipal( ControladorGuiPrincipal controlador ) {
        this.controladorPrincipal = controlador;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelUsuario = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelLogoUnivalle = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelLogoUV = new javax.swing.JLabel();
        jButtonSalirAplicacion = new javax.swing.JButton();
        jTabbedPanePrincipal = new javax.swing.JTabbedPane();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuConfiguracion = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemAyuda = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(GuiPrincipal.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanelUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelUsuario.setName("jPanelUsuario"); // NOI18N

        jPanel2.setBackground(resourceMap.getColor("jPanel2.background")); // NOI18N
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogoUnivalle.setName("jLabelLogoUnivalle"); // NOI18N
        jPanel2.add(jLabelLogoUnivalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel7.setFont(resourceMap.getFont("jLabel7.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jSeparator4.setName("jSeparator4"); // NOI18N
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, 140, 10));

        jLabelLogoUV.setIcon(resourceMap.getIcon("jLabelLogoUV.icon")); // NOI18N
        jLabelLogoUV.setText(resourceMap.getString("jLabelLogoUV.text")); // NOI18N
        jLabelLogoUV.setName("jLabelLogoUV"); // NOI18N
        jPanel2.add(jLabelLogoUV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jButtonSalirAplicacion.setIcon(resourceMap.getIcon("jButtonSalirAplicacion.icon")); // NOI18N
        jButtonSalirAplicacion.setText(resourceMap.getString("jButtonSalirAplicacion.text")); // NOI18N
        jButtonSalirAplicacion.setName("jButtonSalirAplicacion"); // NOI18N
        jButtonSalirAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirAplicacionActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSalirAplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, -1));

        javax.swing.GroupLayout jPanelUsuarioLayout = new javax.swing.GroupLayout(jPanelUsuario);
        jPanelUsuario.setLayout(jPanelUsuarioLayout);
        jPanelUsuarioLayout.setHorizontalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelUsuarioLayout.setVerticalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(378, Short.MAX_VALUE))
        );

        jTabbedPanePrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPanePrincipal.setName("jTabbedPanePrincipal"); // NOI18N

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setName("jSeparator1"); // NOI18N

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenuArchivo.setText(resourceMap.getString("jMenuArchivo.text")); // NOI18N
        jMenuArchivo.setName("jMenuArchivo"); // NOI18N

        jMenuItemNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemNuevo.setIcon(resourceMap.getIcon("jMenuItemNuevo.icon")); // NOI18N
        jMenuItemNuevo.setText(resourceMap.getString("jMenuItemNuevo.text")); // NOI18N
        jMenuItemNuevo.setName("jMenuItemNuevo"); // NOI18N
        jMenuItemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemNuevo);

        jMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSalir.setIcon(resourceMap.getIcon("jMenuItemSalir.icon")); // NOI18N
        jMenuItemSalir.setText(resourceMap.getString("jMenuItemSalir.text")); // NOI18N
        jMenuItemSalir.setName("jMenuItemSalir"); // NOI18N
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBar1.add(jMenuArchivo);

        jMenuConfiguracion.setText(resourceMap.getString("jMenuConfiguracion.text")); // NOI18N
        jMenuConfiguracion.setName("jMenuConfiguracion"); // NOI18N

        jMenu1.setText(resourceMap.getString("jMenu1.text")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText(resourceMap.getString("jRadioButtonMenuItem2.text")); // NOI18N
        jRadioButtonMenuItem2.setName("jRadioButtonMenuItem2"); // NOI18N
        jMenu1.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText(resourceMap.getString("jRadioButtonMenuItem1.text")); // NOI18N
        jRadioButtonMenuItem1.setName("jRadioButtonMenuItem1"); // NOI18N
        jMenu1.add(jRadioButtonMenuItem1);

        jMenuConfiguracion.add(jMenu1);

        jMenuBar1.add(jMenuConfiguracion);

        jMenuAyuda.setText(resourceMap.getString("jMenuAyuda.text")); // NOI18N
        jMenuAyuda.setName("jMenuAyuda"); // NOI18N

        jMenuItemAyuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemAyuda.setIcon(resourceMap.getIcon("jMenuItemAyuda.icon")); // NOI18N
        jMenuItemAyuda.setText(resourceMap.getString("jMenuItemAyuda.text")); // NOI18N
        jMenuItemAyuda.setName("jMenuItemAyuda"); // NOI18N
        jMenuAyuda.add(jMenuItemAyuda);

        jMenuItem1.setIcon(resourceMap.getIcon("jMenuItem1.icon")); // NOI18N
        jMenuItem1.setText(resourceMap.getString("jMenuItem1.text")); // NOI18N
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItem1);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPanePrincipal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                    .addComponent(jPanelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenuItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoActionPerformed
    controladorPrincipal.crearGuiDustCart();
}//GEN-LAST:event_jMenuItemNuevoActionPerformed

private void jButtonSalirAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirAplicacionActionPerformed
    controladorPrincipal.salir();
}//GEN-LAST:event_jButtonSalirAplicacionActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    controladorPrincipal.acercaDe();
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
    controladorPrincipal.crearGuiPrestamo();
}//GEN-LAST:event_jMenuItemSalirActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalirAplicacion;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelLogoUV;
    private javax.swing.JLabel jLabelLogoUnivalle;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConfiguracion;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAyuda;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPanePrincipal;
    // End of variables declaration//GEN-END:variables

    /**
     * Conocer el numero de componentes que estan adicionados en el tab
     * @return numeroComponentes El numero de componentes
     */
    public int getNumerotabs() {
        numeroComponentes = jTabbedPanePrincipal.getTabCount();
        return numeroComponentes;          
    }

    /**
     * Configura las propiedades de los JTabbedPane que se adicionan a la gui.
     * @param tabPane El JTabbedPane que se va a configurar.
     */
    public void configurarJTabbedPane(String tituloTab, Component gui) {
        jTabbedPanePrincipal.add(tituloTab, gui ); // el titulo del TabComponent y el componente a mostrar
        jTabbedPanePrincipal.setTabLayoutPolicy(JTabbedPane.WRAP_TAB_LAYOUT);
    }

    public void initTabComponent(int indiceTab) {
        jTabbedPanePrincipal.setTabComponentAt(indiceTab, new ButtonTabComponent(jTabbedPanePrincipal));
    }
}
